# Generated by Django 6.0.4 on 2026-06-09 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('situacao_trabalho', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('empreendedor', 'Sou empreendedor')], max_length=20)),
                ('renda_familiar', models.CharField(choices=[('menos_um', 'Menos de um salário mínimo'), ('um', 'Um salário mínimo'), ('um_a_dois', 'De um a dois salários mínimos'), ('acima_dois', 'Acima de dois salários mínimos')], max_length=20)),
                ('num_membros', models.IntegerField(choices=[(1, '1 integrante'), (2, '2 integrantes'), (3, '3 integrantes'), (4, '4 integrantes'), (5, '5 integrantes'), (6, 'Acima de 5 integrantes')])),
                ('termo_aceito', models.BooleanField(default=False)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('comunidade', models.CharField(blank=True, max_length=100, null=True)),
                ('organizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('redes_sociais', models.CharField(blank=True, max_length=200, null=True)),
                ('cota', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('setor', models.CharField(blank=True, help_text='Setor/Região do presidente', max_length=100, null=True)),
                ('visitas', models.IntegerField(default=0, help_text='Quantidade de visitas realizadas')),
                ('eventos', models.IntegerField(default=0, help_text='Quantidade de eventos realizados')),
                ('penalizacao', models.IntegerField(default=0, help_text='Pontos de penalização (desconta do score)')),
                ('meta_familias', models.IntegerField(default=0, help_text='Meta de famílias a serem atendidas/recrutadas')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presidente_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
