# Generated by Django 6.0.4 on 2026-05-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presidentes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presidente',
            old_name='setor',
            new_name='comunidade',
        ),
        migrations.AddField(
            model_name='presidente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='presidente',
            name='endereco',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presidente',
            name='num_membros',
            field=models.IntegerField(choices=[(1, '1 integrante'), (2, '2 integrantes'), (3, '3 integrantes'), (4, '4 integrantes'), (5, '5 integrantes'), (6, 'Acima de 5 integrantes')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presidente',
            name='organizacao',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presidente',
            name='redes_sociais',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presidente',
            name='renda_familiar',
            field=models.CharField(choices=[('menos_um', 'Menos de um salário mínimo'), ('um', 'Um salário mínimo'), ('um_a_dois', 'De um a dois salários mínimos'), ('acima_dois', 'Acima de dois salários mínimos')], default='menos_um', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presidente',
            name='situacao_trabalho',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('empreendedor', 'Sou empreendedor')], default='sim', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presidente',
            name='telefone',
            field=models.CharField(default='sim', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presidente',
            name='termo_aceito',
            field=models.BooleanField(default=False),
        ),
    ]
