# Generated by Django 6.0.4 on 2026-06-06 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presidentes', '0002_rename_setor_presidente_comunidade_presidente_cnpj_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presidente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presidente_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
