# Generated by Django 6.0.4 on 2026-06-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presidentes', '0002_rename_setor_presidente_comunidade_presidente_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidente',
            name='eventos',
            field=models.IntegerField(default=0, help_text='Quantidade de eventos realizados'),
        ),
        migrations.AddField(
            model_name='presidente',
            name='penalizacao',
            field=models.IntegerField(default=0, help_text='Pontos de penalização (desconta do score)'),
        ),
        migrations.AddField(
            model_name='presidente',
            name='setor',
            field=models.CharField(blank=True, help_text='Setor/Região do presidente', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='presidente',
            name='visitas',
            field=models.IntegerField(default=0, help_text='Quantidade de visitas realizadas'),
        ),
    ]
