# Generated by Django 6.0.4 on 2026-06-07 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presidentes', '0003_presidente_eventos_presidente_penalizacao_and_more'),
        ('presidentes', '0003_presidente_user'),
    ]

    operations = [
    ]
