# Generated by Django 6.0.4 on 2026-06-09 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familias', '0001_initial'),
        ('presidentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('rascunho', 'Rascunho'), ('encerrado', 'Encerrado')], default='rascunho', max_length=20)),
                ('prazo', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Numero'), ('booleano', 'Sim/Nao'), ('data', 'Data'), ('selecao_unica', 'Selecao unica'), ('selecao_multipla', 'Selecao multipla')], max_length=20)),
                ('obrigatoria', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='formularios.ciclo')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='formularios.pergunta')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RespostaCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completo', 'Completo'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('respondido_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='formularios.ciclo')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='familias.familia')),
                ('presidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presidentes.presidente')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True)),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('valor_data', models.DateField(blank=True, null=True)),
                ('opcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_unicas', to='formularios.opcao')),
                ('opcoes', models.ManyToManyField(blank=True, related_name='respostas_multiplas', to='formularios.opcao')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='formularios.pergunta')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='formularios.respostaciclo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='respostaciclo',
            constraint=models.UniqueConstraint(fields=('ciclo', 'familia'), name='unique_resposta_por_familia_ciclo'),
        ),
    ]
