# Generated by Django 6.0.4 on 2026-05-13 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familias', '0001_initial'),
        ('presidentes', '0002_rename_setor_presidente_comunidade_presidente_cnpj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('rascunho', 'Rascunho'), ('encerrado', 'Encerrado')], default='rascunho', max_length=20)),
                ('prazo', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completo', 'Completo'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('respondido_em', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='formularios.ciclo')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familias.familia')),
                ('presidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presidentes.presidente')),
            ],
        ),
    ]
