# Generated by Django 6.0.4 on 2026-06-11 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
        ('presidentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostaciclo',
            name='presidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presidentes.presidente'),
        ),
    ]
