# Generated by Django 6.0.4 on 2026-06-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_add_questions_and_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostaciclo',
            name='status',
            field=models.CharField(choices=[('completo', 'Completo'), ('pendente', 'Pendente')], default='pendente', max_length=20),
        ),
    ]
