# Generated by Django 6.0.4 on 2026-06-06 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0002_add_status_fields'),
        ('formularios', '0003_alter_respostaciclo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostaciclo',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='familias.familia'),
        ),
    ]
