# Generated by Django 6.0.4 on 2026-06-15 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0003_familia_acoes_concluidas_familia_pontos_participacao'),
        ('formularios', '0004_alter_respostaciclo_familia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('categoria', models.CharField(choices=[('status', 'Alteração de Status'), ('comunidade', 'Comunicado Geral'), ('ranking', 'Ranking')], default='status', max_length=30)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='familias.familia')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
