# Generated by Django 6.0.4 on 2026-06-09 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presidentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('comunidade', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('melhor_horario', models.CharField(blank=True, max_length=100)),
                ('renda_familiar', models.CharField(choices=[('sem_renda', 'Sem renda fixa'), ('ate_meio', 'Até meio salário mínimo'), ('ate_um', 'Até um salário mínimo'), ('um_a_dois', 'De 1 a 2 salários mínimos'), ('mais_dois', 'Mais de 2 salários mínimos')], max_length=20)),
                ('num_membros', models.IntegerField()),
                ('mae_solo', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('sem_filhos', 'Não tenho filhos')], max_length=20)),
                ('num_filhos', models.IntegerField(default=0)),
                ('bolsa_familia', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('lista_espera', 'Lista de espera')], default='pendente', max_length=20)),
                ('aprovada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('presidente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familias', to='presidentes.presidente')),
            ],
        ),
    ]
