# Generated by Django 6.0.4 on 2026-06-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='num_filhos',
            new_name='eventos_compareceu',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='aprovada',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='bolsa_familia',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='comunidade',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='mae_solo',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='melhor_horario',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='renda_familiar',
        ),
        migrations.AddField(
            model_name='familia',
            name='perfil',
            field=models.CharField(choices=[('mae_solo', 'Mãe solo'), ('baixa_renda', 'Baixa renda'), ('mais_3_filhos', '+3 filhos'), ('idosos', 'Idosos'), ('nenhum', 'Nenhum perfil específico')], default='nenhum', max_length=20),
        ),
        migrations.AddField(
            model_name='familia',
            name='total_eventos',
            field=models.IntegerField(default=9),
        ),
    ]
