# Generated by Django 6.0.4 on 2026-06-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0002_add_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='acoes_concluidas',
            field=models.IntegerField(default=0, help_text='Quantidade de ações comunitárias feitas'),
        ),
        migrations.AddField(
            model_name='familia',
            name='pontos_participacao',
            field=models.IntegerField(default=0, help_text='Pontos acumulados por engajamento'),
        ),
    ]
