# Generated by Django 6.0.4 on 2026-06-14 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0002_add_status_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='acoes_concluidas',
            field=models.IntegerField(default=0, help_text='Quantidade de ações comunitárias feitas'),
        ),
        migrations.AddField(
            model_name='familia',
            name='pontos_participacao',
            field=models.IntegerField(default=0, help_text='Pontos acumulados por engajamento'),
        ),
        migrations.AddField(
            model_name='familia',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familia_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
