# Generated by Django 6.0.4 on 2026-06-10 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0002_rename_num_filhos_familia_eventos_compareceu_and_more'),
        ('presidentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='eventos_compareceu',
            field=models.IntegerField(default=0, help_text='Quantos eventos a família compareceu'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='num_membros',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='familia',
            name='presidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familias', to='presidentes.presidente'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='total_eventos',
            field=models.IntegerField(default=9, help_text='Total de eventos do período'),
        ),
    ]
