# Generated by Django 6.0.4 on 2026-06-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0003_familia_acoes_concluidas_familia_pontos_participacao'),
        ('familias', '0003_familia_user'),
    ]

    operations = [
    ]
