# Generated by Django 6.0.4 on 2026-06-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0003_familia_atualizado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='criado_em',
        ),
        migrations.AlterField(
            model_name='familia',
            name='eventos_compareceu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='familia',
            name='total_eventos',
            field=models.IntegerField(default=9),
        ),
    ]
