# Generated by Django 6.0.4 on 2026-06-16 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0003_familia_acoes_concluidas_familia_pontos_participacao_and_more'),
        ('familias', '0004_merge_20260615_1753'),
        ('familias', '0004_merge_20260615_1823'),
    ]

    operations = [
    ]
