# Generated by Django 6.0.4 on 2026-06-11 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0004_remove_familia_atualizado_em_and_more'),
    ]

    operations = [
    ]
