# Generated by Django 6.0.4 on 2026-06-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0005_auto_20260610_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='comunidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='familia',
            name='endereco',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='familia',
            name='municipio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='familia',
            name='num_filhos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familia',
            name='recebe_beneficio',
            field=models.BooleanField(default=False, help_text='Recebe Bolsa Família ou outro benefício social?'),
        ),
    ]
