# Generated by Django 6.0.4 on 2026-06-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0006_familia_comunidade_familia_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='aprovada',
            field=models.BooleanField(default=False, help_text='Define se a família está aprovada'),
        ),
    ]
