# Generated by Django 6.0.4 on 2026-06-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0007_familia_aprovada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='aprovada',
        ),
        migrations.AlterField(
            model_name='familia',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('completo', 'Completo')], default='pendente', max_length=20),
        ),
    ]
