# Generated by Django 6.0.4 on 2026-06-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0008_remove_familia_aprovada_alter_familia_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='aprovada',
            field=models.BooleanField(default=False),
        ),
    ]
