# Generated by Django 6.0.4 on 2026-06-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0009_familia_aprovada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='aprovada',
            field=models.BooleanField(default=False, help_text='Marca se a família foi aprovada (independente do status)'),
        ),
    ]
